version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
      - redis-server
    command: bash -c "
      cd /app/src
      && alembic upgrade head
      && python3 /app/src/main.py"
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
      - docs:${DOCUMENT_DIR}
      - ${SSL_KEY_FILE}:/app/key_file.pem
      - ${SSL_CERT_FILE}:/app/ssl_cert.pem


  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  dbeaver:
    image: dbeaver/cloudbeaver
    volumes:
      - dbeaver:/opt/cloudbeaver/workspace
    ports:
      - "8978:8978"

  redis-server:
    image: redis/redis-stack-server
    restart: always
    command: redis-server --protected-mode no

volumes:
  db:
  dbeaver:
  docs:
